name: fairshare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc_concurrency: 0.2.2
  cached_network_image: 3.4.1
  cupertino_icons: 1.0.6
  device_info: ^2.0.3
  enhanced_http: 4.2.3
  equatable: 2.0.5
  form_validator: 2.1.1
  firebase_auth: 5.3.0
  firebase_core: 3.5.0
  firebase_messaging: 15.1.2
  font_awesome_flutter: 10.1.0
  fluttertoast: 8.2.8
  flutter_bloc: 8.1.2
  flutter_dotenv: 5.0.2
  flutter_facebook_auth: 7.1.1
  flutter_html: 3.0.0-beta.2
  flutter_phoenix: 1.1.1
  flutter_secure_storage: 9.2.2
  flutter_spinkit: 5.2.1
  flutter_svg: 2.0.10+1
  google_fonts: 6.2.1
  google_sign_in: 6.2.1
  image_gallery_saver: 2.0.3
  image_picker: 1.1.2
  infinite_scroll_pagination: 4.0.0
  intl: 0.19.0
  intl_phone_number_input: 0.7.4
  json_annotation: 4.8.0
  optional: 6.1.0+1
  package_info_plus: 4.2.0
  page_transition: 2.0.9
  path_provider: 2.1.4
  readmore: 3.0.0
  responsive_sizer: 3.1.1
  sign_in_with_apple: 6.1.2
  shimmer: 2.0.0
  upgrader: 8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3
  faker: 2.1.0
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  flutter_native_splash: 2.2.19
  json_serializable: 6.6.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/icons/
    - assets/images/

  # To add assets to your application, add an assets section, like this:

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/images/logo_splash.png

# flutter_launcher_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "assets/images/launcher.png"